### ISSUE TITLE
GitHub::Repositories::Collaborator create fails

### ISSUE THREAD

**Issue by ericzbeard** [aws-ia/cloudformation-github-resource-providers#11]
Fails in both contract testing and stack creation. It creates the invitation successfully in the organization, but then immediately fails with `AlreadyExists`.

```
Resource handler returned message: "Error: Resource of type 'GitHub::Repositories::Collaborator' 
with identifier 'Collab' already exists." 
(RequestToken: 1ab35620-a3ea-bcec-6c21-478165ff5286, HandlerErrorCode: AlreadyExists)
```

**Comment by lukiwlosek** [comment]
Contract test failed as the get() method always returned something for public repositories, [this PR fixes this.](https://github.com/aws-ia/cloudformation-github-resource-providers/pull/14)
