### ISSUE TITLE
Move GitHubAccess to typeConfiguration

### ISSUE THREAD

**Issue by benbridts** [aws-ia/cloudformation-github-resource-providers#20]
It would be nice if the GitHubAccess would not have to be part of the deployed template, but instead could be configured per-account.

See https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/resource-type-model.html#resource-type-howto-configuration

I'm not sure how this would work with backward compatibility, but both as an example and for new users, this would be a better experience.

**Comment by ericzbeard** [comment]
It's not part of the deployed template, is it? It's in the schema but only referenced from the type config, not from properties.

**Comment by benbridts** [comment]
You'e right! I misread the template
