### ISSUE TITLE
GitHub::Repositories::Secret and  GitHub::Organizations::Secret are not published in CloudFormation

### ISSUE THREAD

**Issue by FlorentCollin** [aws-ia/cloudformation-github-resource-providers#40]
Hello, while trying to activate the extensions, we noticed that two of them are not published yet.

The following extensions are not published in Cloudformation:
 - GitHub::Repositories::Secret
 - GitHub::Organizations::Secret

Also the [GitHub::Organizations::Secret README](https://github.com/aws-ia/cloudformation-github-resource-providers/blob/main/GitHub-Organizations-Secret/README.md) title is incorrect because at the moment it's the  README title of `GitHub::Repositories::Webhook`.

**Comment by CloudChoom** [comment]
@FlorentCollin thank you. We're looking into this.

**Comment by CloudChoom** [comment]
@FlorentCollin The issue has been identified and resolved. These resources should now be published on the Registry and are available for activation.

The typo in the README should also be fixed once this PR is approved: https://github.com/aws-ia/cloudformation-github-resource-providers/pull/41
